### ISSUE TITLE
Sometimes Kuiper hangs on reboot

### ISSUE THREAD

**Issue by SRaus** [analogdevicesinc/adi-kuiper-gen#25] opened 2020-07-30 07:26 UTC
Sometimes, when I hit a 'reboot' on a PRI that runs Kuiper, it looks that the RPI hangs. 
But actually, the reboot process takes about 1/5 minutes to finish. 
The issue was reproduced randomly on RPI3 RevB.

**Comment by commodo** [comment] 2020-11-10 10:54
> The issue was reproduced randomly on RPI3 RevB.

Let's close this for now.
Randomly is too much work to identify.
If we can make this reproduce reliably, then there's something to go on.
RPi randomly hangs on reboots even with their own image.

And nothing has been done on this since July 30th 2020.

**Closed by commodo** 2020-11-10 10:54 UTC
